{{- range $agentpools := .Values.agentpools }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AzureManagedMachinePool
metadata:
  name: {{ $agentpools.name }}
spec:
  mode: {{ $agentpools.mode }}
  osDiskSizeGB: {{ $agentpools.osDiskSizeGB }}
  sku: {{ $agentpools.sku }}
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachinePool
metadata:
  name: {{ $agentpools.name }}
spec:
  clusterName: {{ $.Values.cluster.name }}
  replicas: {{ $agentpools.nodecount }}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: {{ $.Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: AzureManagedMachinePool
        name: {{ $agentpools.name }}
        namespace: {{ $.Release.Namespace }}
      version: {{ $.Values.controlplane.kubernetes_version }}
---
{{- end }}