apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: {{ $.Values.identity.clusterIdentityName }} 
spec:
  allowedNamespaces: {}
  clientID: {{ $.Values.identity.clientId }} 
  tenantID: {{ $.Values.identity.tenantId }}
  resourceID: {{ $.Values.cluster.resourceGroupName }}
  type: UserAssignedMSI